name: ML
channels:
  - conda-forge
#   - anaconda
  - defaults
dependencies:
  - python=3.9.7
  - scikit-learn=1.0.2
  - matplotlib=3.5.0
  - pandas=1.3.4
  - seaborn=0.11.1
  - pip
  - pip:
    - mlrose-hiive
